"""empty message

Revision ID: 7c178fb5854e
Revises: 13dc4109d255
Create Date: 2026-04-15 11:36:47.818665

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c178fb5854e"
down_revision: Union[str, Sequence[str], None] = "13dc4109d255"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "idempotency_key",
            existing_type=sa.UUID(),
            type_=sa.String(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "idempotency_key",
            existing_type=sa.String(),
            type_=sa.UUID(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
