"""empty message

Revision ID: c2f08b44d468
Revises: c858be69fee4
Create Date: 2026-04-14 22:49:07.903284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2f08b44d468"
down_revision: Union[str, Sequence[str], None] = "c858be69fee4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inbox", schema=None) as batch_op:
        batch_op.alter_column(
            "idempotency_key",
            existing_type=sa.UUID(),
            type_=sa.String(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inbox", schema=None) as batch_op:
        batch_op.alter_column(
            "idempotency_key",
            existing_type=sa.String(),
            type_=sa.UUID(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
