"""empty message

Revision ID: c858be69fee4
Revises: 1384eb510cbf
Create Date: 2026-04-14 15:00:59.668915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c858be69fee4"
down_revision: Union[str, Sequence[str], None] = "1384eb510cbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inbox", schema=None) as batch_op:
        batch_op.alter_column(
            "id", existing_type=sa.VARCHAR(), type_=sa.UUID(), existing_nullable=False
        )
        batch_op.alter_column(
            "idempotency_key",
            existing_type=sa.VARCHAR(),
            type_=sa.UUID(),
            existing_nullable=True,
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "idempotency_key",
            existing_type=sa.VARCHAR(),
            type_=sa.UUID(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "idempotency_key",
            existing_type=sa.UUID(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    with op.batch_alter_table("inbox", schema=None) as batch_op:
        batch_op.alter_column(
            "idempotency_key",
            existing_type=sa.UUID(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "id", existing_type=sa.UUID(), type_=sa.VARCHAR(), existing_nullable=False
        )

    # ### end Alembic commands ###
