from __future__ import annotations

import asyncio
import json
from copy import deepcopy
from dataclasses import asdict, dataclass, fields
from typing import Any, Callable, Self
from aiohttp import ClientError, ClientResponse, ClientSession, helpers

from src.utils.logger import logger


type RouteOptiU = PathBuilder | list[Any] | Any | None
type QueryOptiU = ParamsBuilder | dict[str, Any] | None
type DictOptiU = CollectionBuilder | dict[str, Any] | None
type OnCodeOptiU = CollectionBuilder | dict[int, Callable] | None
type OptionalConfig = QueryConfig | None


class APIError(Exception):
    def __init__(
        self,
        code: int,
        api_name: str,
        status_text: str | None = None,
        response_body: dict | list | None = None,
    ):
        self._code = code
        self._api_name = api_name
        self._status_text = status_text
        self._response_body = response_body
        base = f"[{status_text}] {api_name} API returns {code}"
        if response_body is None:
            super().__init__(f"{base}!")
        else:
            import json

            super().__init__(f"{base} with body: {json.dumps(response_body, indent=2)}")

    @property
    def body(self):
        return self._response_body


class ErrorCodeHandler:
    _DEFAULT_MESSAGES = {
        400: "Bad Request",
        401: "Unauthorized",
        403: "Forbidden",
        404: "Not Found",
        409: "Conflict",
        500: "Internal Server Error",
        501: "Not Implemented",
        502: "Bad Gateway",
        503: "Service Unavailable",
        504: "Gateway Timeout",
    }

    def __init__(self, api_name: str):
        self._api_name = api_name
        self._error_classes = {}

    def __getitem__(self, code: int):
        if code not in self._DEFAULT_MESSAGES:
            raise KeyError(f"HTTP error code {code} is not supported")

        if code not in self._error_classes:
            status_text = self._DEFAULT_MESSAGES[code]
            api_name = self._api_name

            class DynamicError(APIError):
                def __init__(self, response_body: dict | list | None = None):
                    super().__init__(code, api_name, status_text, response_body)

            DynamicError.__name__ = f"{api_name}ReturnCode{code}AutoGeneratedError"
            DynamicError.__qualname__ = DynamicError.__name__
            self._error_classes[code] = DynamicError

        return self._error_classes[code]

    def __call__(self, code: int, body: dict | list | None = None):
        error_class = self.__getitem__(code)
        return error_class(body)


@dataclass
class QueryConfig:
    """Конфигурация запроса"""

    content_type: str = "application/json"
    raise_on_error: bool | None = None
    timeout: float | None = None
    trailing_slash: bool | None = None
    with_status_code: bool | None = None
    max_retries: int = 0

    def __add__(self, other: OptionalConfig = None) -> "QueryConfig":
        """Объединяет два конфига, возвращает новый, параметры второго приоритетнее"""
        if other is None:
            return QueryConfig(**asdict(self))

        if isinstance(other, dict):
            other = QueryConfig(**other)

        if not isinstance(other, QueryConfig):
            raise TypeError(f"Can only add QueryConfig, not {type(other)}")

        result = QueryConfig(**asdict(self))

        for field in fields(self):
            other_value = getattr(other, field.name)
            if other_value is not None:
                setattr(result, field.name, other_value)

        return result


class CollectionBuilder:
    """Базовый менеджер для всех коллекций"""

    def __init__(self, data: Any = None):
        self.base = deepcopy(data) if data is not None else self._default()
        self.container = self._default()

    def _default(self):
        return {}

    def add(self, elem: dict):
        self.container.update(elem)

    def get(self) -> Any:
        if isinstance(self.base, list):
            return self.base + self.container
        return {**self.base, **self.container}

    def view(self) -> Self:
        res = self.__class__(self.get())
        self.flush()
        return res

    def flush(self) -> Self:
        self.container = self._default()
        return self

    def clear(self) -> Self:
        self.base = self._default()
        self.container = self._default()
        return self


class PathBuilder(CollectionBuilder):
    """Менеджер для пути URL"""

    def _default(self):
        return []

    def add(self, elem: list | str | int):
        if isinstance(elem, str):
            elem = elem.lstrip("/").rstrip("/").split("/")
        if isinstance(elem, list):
            self.container.extend(elem)
        else:
            self.container.append(str(elem))

    def build(self) -> str:
        return f"{'/'.join(self.base)}/{'/'.join(self.container)}".lstrip("/").rstrip(
            "/"
        )


class ParamsBuilder(CollectionBuilder):
    """Менеджер для query параметров"""

    def build(self) -> str:
        src = self.get()
        if not src:
            return ""

        parts = []
        for k, v in src.items():
            if isinstance(v, (dict, list)):
                v = json.dumps(v, separators=(",", ":"))
            parts.append(f"{helpers.quote(str(k))}={helpers.quote(str(v))}")
        return f"?{'&'.join(parts)}"


class ResponseError(Exception):
    """Исключение для ошибок HTTP"""

    def __init__(self, status: int, message: str, data: Any = None):
        self.status = status
        self.message = message
        self.data = data
        super().__init__(f"HTTP {status}: {message}")


class RequestBuilder:
    """Основной класс для выполнения HTTP запросов"""

    def __init__(
        self,
        session: ClientSession,
        config: OptionalConfig = None,
        route: RouteOptiU = None,
        query: QueryOptiU = None,
        header: DictOptiU = None,
        body: DictOptiU = None,
        on_code: OnCodeOptiU = None,
    ):
        self.session = session
        self.config = config or QueryConfig()

        self.route = self._ensure(route, PathBuilder, [])
        self.query = self._ensure(query, ParamsBuilder, {})
        self.header = self._ensure(header, CollectionBuilder, {})
        self.body = self._ensure(body, CollectionBuilder, {})
        self.on_code = self._ensure(on_code, CollectionBuilder, {})

    @staticmethod
    def _ensure(obj, cls, default):
        if obj is None:
            return cls(default)
        return obj if isinstance(obj, cls) else cls(obj)

    def view(self) -> Self:
        """Создать копию RequestBuilder с текущими параметрами"""
        res = self.__class__(
            session=self.session,
            config=self.config,
            route=self.route.view(),
            query=self.query.view(),
            header=self.header.view(),
            body=self.body.view(),
            on_code=self.on_code.view(),
        )
        self.flush()
        return res

    def flush(self) -> Self:
        """Сбросить временные параметры"""
        self.route.flush()
        self.query.flush()
        self.header.flush()
        self.body.flush()
        self.on_code.flush()

    def at(self, part: Any) -> Self:
        """Добавить часть к пути URL"""
        self.route.add(part)
        return self.view()

    def where(self, params: dict[str, Any]) -> Self:
        """Добавить query параметры"""
        self.query.add(params)
        return self.view()

    def via(self, headers: dict[str, Any]) -> Self:
        """Добавить заголовки"""
        self.header.add(headers)
        return self.view()

    def with_body(self, body: dict[str, Any]) -> Self:
        """Добавить тело запроса"""
        self.body.add(body)
        return self.view()

    def on(self, mapping: dict[int, Callable]) -> Self:
        """Добавить обработчики для статус-кодов"""
        self.on_code.add(mapping)
        return self.view()

    def prepare_url(self, config: QueryConfig, *, no_query: bool = False) -> str:
        """Подготовить полный URL"""
        full_path = self.route.build().rstrip("/")
        if config.trailing_slash is not None and config.trailing_slash:
            full_path += "/"
        query_str = self.query.build()
        if no_query:
            return f"{full_path}"
        else:
            return f"{full_path}{query_str}"

    async def _handle_response(self, resp: ClientResponse, config: QueryConfig) -> Any:
        """Обработать HTTP ответ"""
        text = await resp.text()

        parsed = text
        if text.strip() and (text.strip().startswith(("{", "["))):
            try:
                parsed = json.loads(text)
            except json.JSONDecodeError:
                pass

        handlers = self.on_code.get()
        if resp.status in handlers:
            result = handlers[resp.status](resp, parsed)
            if result is not None:
                return result

        if config.raise_on_error and resp.status >= 400:
            raise ResponseError(
                status=resp.status,
                message=f"HTTP error {resp.status}",
                data=parsed,
            )

        if config.with_status_code:
            return {"status": resp.status, "data": parsed}

        return parsed

    async def fetch(self, method: str = "GET", config: OptionalConfig = None) -> Any:
        """Выполнить HTTP запрос с произвольным методом"""
        config = self.config + config

        payload = {}
        payload["method"] = method
        payload["url"] = self.prepare_url(config)

        headers = json.loads(json.dumps(self.header.get(), default=str))
        body = json.loads(json.dumps(self.body.get(), default=str))

        if "Content-Type" not in headers:
            headers["Content-Type"] = config.content_type
        payload["headers"] = headers

        if headers["Content-Type"].startswith("application/json"):
            payload["json"] = body
        else:
            payload["body"] = body

        last_error = None
        for attempt in range(config.max_retries + 1):
            try:
                async with self.session.request(
                    **payload,
                    timeout=config.timeout,
                ) as resp:
                    result = await self._handle_response(resp, config)

                return result

            except (ClientError, asyncio.TimeoutError, ResponseError) as e:
                last_error = e
                if attempt == config.max_retries:
                    raise
                if attempt < config.max_retries:
                    logger.warning(
                        f"Request failed (attempt {attempt + 1}/{config.max_retries + 1}): {str(e)}"
                    )
                    continue

        if isinstance(last_error, ResponseError):
            raise last_error
        raise ResponseError(
            status=0,
            message=f"Request failed after {config.max_retries + 1} attempts",
            data=str(last_error),
        )

    async def get(self, config: OptionalConfig = None) -> Any:
        """Выполнить GET запрос"""
        return await self.fetch("GET", config)

    async def post(self, config: OptionalConfig = None) -> Any:
        """Выполнить POST запрос"""
        return await self.fetch("POST", config)

    async def put(self, config: OptionalConfig = None) -> Any:
        """Выполнить PUT запрос"""
        return await self.fetch("PUT", config)

    async def patch(self, config: OptionalConfig = None) -> Any:
        """Выполнить PATCH запрос"""
        return await self.fetch("PATCH", config)

    async def delete(self, config: OptionalConfig = None) -> Any:
        """Выполнить DELETE запрос"""
        return await self.fetch("DELETE", config)
